
	<div class = conteudo>
		<!-- CABEÇALHO DO SITE -->
		<div class = "areaSocial">
		<!-- LINKS DAS REDES SOCIAIS-->
			<p style="text-align: right;">
				<a class = "social" href = "https://www.facebook.com/politechpc/?fref=ts" target="_blank">
					<img src = "img/facebook.png" border = "0" alt>
				</a>
				<a class = "social" href = "#">
					<img src = "img/twitter.png" border = "0" alt>
				</a>
				<a class = "social" href = "#">
					<img src = "img/rss.png" border = "0" alt>
				</a>
				<a class = "social" href = "#">
					<img src = "img/googleplus.png" border = "0" alt>
				</a>
			</p>
		<!-- FIM DOS LINKS DAS REDES SOCIAIS-->
		</div>
			
			<br/> <br/> <br/> <br/>  <br/> <br/> 
			</a>
